global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "blackbox_api"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://firstapp-backend:8080/actuator/health  # API endpoint to probe; adjust if different
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: "api_metrics"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["firstapp-backend:8080"]
