# k8s/frontend-user-rayong.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-user
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-user
  template:
    metadata:
      labels:
        app: frontend-user
    spec:
      containers:
      - name: frontend-user
        image: filmfilm/foodstore-user-frontend:${IMAGE_VERSION}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf-user-rayong
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-user
  namespace: production
spec:
  type: NodePort
  selector:
    app: frontend-user
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
